MODULE UBKLSTAR
DESCRIPTION IDL L* CALCULATER
VERSION UBKL* 0.0.0.2
SOURCE Kyungguk Min, NJIT
BUILD_DATE April 12, 2013
PROCEDURE	UBK_COTRANS_C		9	9
PROCEDURE	UBK_TS_FIELD_C		12	12
PROCEDURE	UBK_FIELD_LINE_C	20	20
PROCEDURE	UBK_LSTAR_C		23	23
