MODULE IDL_LSTAR
DESCRIPTION IDL UBKL* CALCULATER DLM
VERSION IDL UBKL* 0.0.0.3
SOURCE Kyungguk Min, Auburn University
BUILD_DATE July 10, 2013
PROCEDURE	UBK_COTRANS_C		9	9
PROCEDURE	UBK_TS_FIELD_C		13	13
PROCEDURE	UBK_FIELD_LINE_C	21	21
PROCEDURE	UBK_LSTAR_C		24	24
